# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name : Nome 1

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  inputs:
    buildContext: '$(Build.Repository.LocalPath)'
    containerRegistry: 'DockerHdO'
    repository: 'devgiovannifernandes/ggg'
    command: 'buildAndPush'
    tags: |
      latest
    Dockerfile: '**/Dockerfile'
- publish: $(System.DefaultWorkingDirectory)/stack.yml
  artifact: compose
